### ISSUE TITLE
Could never build source code

### ISSUE THREAD

**Issue by mmayo2112** [AndrewButenko/GoogleAddressAutocomplete_PCF#16]
Did npm install in GoogleAddressAutocomplete_PCF-master folder, then an npm run build, created a solution folder and successfully ran a pac solution init - then an pac solution add-reference and a msbuild /t:restore - but when msbuild:

.nuget\packages\microsoft.powerapps.msbuild.solution\1.3.6\build\Microsoft.PowerApps.MSBuild.Solution.
targets(104,5): error : Project Reference with output path 0, is not a valid PowerApps Component Type  [S:\PCF\GoogleAd
dress\BillingAddressComponent\BillingAddressComponent.cdsproj]

I then imported the managed solution - but after exporting .xml and binding address fields and importing, the control just says "There was a problem"

**Comment by AndrewButenko** [comment]
Hello,
Not sure what is wrong here. Are you aware that there is a solution that you can just download and install - https://github.com/AndrewButenko/GoogleAddressAutocomplete_PCF/releases/tag/1.0.0.1
Andrew

**Comment by KimSte** [comment]
Hi Andrew,

first of all thank you for the solution it works like a charm. But I'd like to adapt it to our requirements (e.g. limit results to certain countries, no comma between street names and housenumber). I am confident that I know where to adapt those settings in the source code, however I am absolutely new to compiling a solution afterwards. 

Could you point me in the right direction or is there any chance that there will be a "localized" version of the solution?

Kim

**Comment by AndrewButenko** [comment]
Hello Kim,
What do you mean by localized version of the solution?
In order to import your version of the control you can use one of 2 following approaches:
https://www.youtube.com/watch?v=2uO2L2xTPkc&t=1s&ab_channel=AndrewButenko
https://www.youtube.com/watch?v=ND3vcxDuodM&ab_channel=AndrewButenko - this is the approach that I used now.
Andrew
