### ISSUE TITLE
Exclamatory Marks

### ISSUE THREAD

**Issue by dim895** [AndrewButenko/GoogleAddressAutocomplete_PCF#17]
Hello Andrew,

First of all thanks for building this solution.

I managed to configure the PCF, got an API from google but unfortunately have exclamatory marks.

I cannot ifgure out where the problem is. Did you envounter this issue?

Thanks in advance,
![Sans titre](https://user-images.githubusercontent.com/53216074/107846700-f3ca6c80-6de5-11eb-9e97-163447a4e844.png)

**Comment by AndrewButenko** [comment]
Hello,
This means you have provided an invalid key.
Andrew

**Comment by dim895** [comment]
Hello Andrew,

Thanks for your quick reply. 

I just pasted a Google Place API, I do not see why it should not work, I will check with google support.

**Comment by AndrewButenko** [comment]
You closed the thread. Does it mean you made it work?

**Comment by dim895** [comment]
Hello Andrew,

Thank you for asking. 

I thouth that it do not work because I had done something wrong in my google account.
It is a trial but il looks like the key is working (As you can see in the statistics attached).

I tried again but cannot make it work.
The key is the Places API right? 

![PCF](https://user-images.githubusercontent.com/53216074/107950001-67ab7700-6f96-11eb-9006-b73ee2118cd4.PNG)

**Comment by dim895** [comment]
Hello Andrew,

I had added a restriction in the API and did not work. Hopefully one of my colleagues helped me out and we activated the key ( including Maps JavaScript API).

Works like a charm now, Thank you

**Comment by AndrewButenko** [comment]
Yeah, Clement got in touch with me, we did the troubleshooting session and came with the solution.
Andrew
