### ISSUE TITLE
Unable to import as solution

### ISSUE THREAD

**Issue by fergupa** [AndrewButenko/GoogleAddressAutocomplete_PCF#7]
Hello- it's quite possible I am doing something wrong.  However, when I try to import the files from GitHub into PowerApps via solutions I get an error stating it needs to be a zip or cab file.  I tried zipping the pcf project file but that did not work either.  Can you please summarize the steps I need to take in order to import it as a solution?  Thanks for all your work - this will be really helpful!!

**Comment by AndrewButenko** [comment]
Hello,
You should use solution (zip file) that is available by following url - https://github.com/AndrewButenko/GoogleAddressAutocomplete_PCF/releases/tag/1.0.0.1
Thanks,
Andrew
