### ISSUE TITLE
After I map those field in form "Classic mode", the autocomplete function still doesn't work. 

### ISSUE THREAD

**Issue by alanchan234** [AndrewButenko/GoogleAddressAutocomplete_PCF#8]
I have imported the zip file as solution and mapped all those field in form under "Change property" what is the next step to make it work?
Thanks

**Comment by AndrewButenko** [comment]
Hello,
Can you please provide a screenshot and mention where did you get API key from?

**Comment by alanchan234** [comment]
![Capture2](https://user-images.githubusercontent.com/58178432/73807300-f1165e00-4806-11ea-843e-847e49225c1d.JPG)
![Capture](https://user-images.githubusercontent.com/58178432/73807314-fbd0f300-4806-11ea-873f-417ca1107942.JPG)

Do you mean where I store the Google API key? I just manually typing it.

**Comment by AndrewButenko** [comment]
Everything looks good for me. What browser do you you use? Is it IE by a chance? I have other issue opened where user has issues using control in IE - https://github.com/AndrewButenko/GoogleAddressAutocomplete_PCF/issues/6

**Comment by alanchan234** [comment]
I am using Chrome.  For this setup, isn't it if I type the full address in the field, then other field (STREET..CITY) will be auto populated only after I saved record? or it will populate suggestions for me to choose?

**Comment by AndrewButenko** [comment]
That's weird. The way it should work is following:
1. You start entering address.
2. Control creates the popup with list of addresses available.
3. Once address is chosen from the popup it is split between other parts of address without the need to save the record. It should happen inline.

Obviously something is going wrong during initialization of the control.
Can you please open Developer Tools (using f12 key), reload the form and check console for any errors? If errors are there can you please post screenshot here?

**Comment by alanchan234** [comment]
I figured out why. Coz I didn't activate the Map java script API in Google. Thanks!
