### ISSUE TITLE
How can I import this component

### ISSUE THREAD

**Issue by malkhawaja** [AndrewButenko/GoogleAddressAutocomplete_PCF#9]
Hi,
How can i import this component as a solution into my CDS environment?

**Comment by AndrewButenko** [comment]
Hello,
I believe the easiest way is to download solution available by url of the latest release - https://github.com/AndrewButenko/GoogleAddressAutocomplete_PCF/releases/tag/1.0.0.1 and import it to CDS using UI.
Andrew

**Comment by malkhawaja** [comment]
Great, thanks.
